# Add your additional Hyprland configurations here
source = ~/.config/hypr/conf/custom/keyboard.conf
source = ~/.config/hypr/conf/custom/gesture.conf
source = ~/.config/hypr/conf/custom/autostart.conf