input {
	touchpad {
		disable_while_typing = true
		natural_scroll = true
		scroll_factor = 1.0
		middle_button_emulation = false
		clickfinger_behavior = false
		tap-to-click = true
		drag_lock = false
	}
	touchdevice {
		transform = 0
		output = 
	}
}