# QuickShell Blur Rules
layerrule = match:namespace quickshell, blur_popups on
layerrule = match:namespace quickshell, blur on
layerrule = match:namespace quickshell, xray on
layerrule = match:namespace quickshell, ignore_alpha 0.79