import QtQuick
import QtQuick.Layouts
import QtQuick.Controls
import Quickshell
import Quickshell.Io
import qs.CustomTheme
import qs.SettingsApp.components

StPage {
    id: page
    heading: "Displays"
    subheading: "Resolution, scale, orientation and arrangement"
    icon: "󰍹"

    property bool active: false
    property bool loading: true
    property bool dirty: false

    onActiveChanged: if (active) loadMonitors.running = true

    ListModel { id: monitors }

    readonly property var rotations: [
        { value: 0, label: "Normal" },
        { value: 1, label: "90°" },
        { value: 2, label: "180°" },
        { value: 3, label: "270°" }
    ]

    Process {
        id: loadMonitors
        property string _buf: ""
        command: ["bash", "-c", "hyprctl monitors all -j"]
        stdout: SplitParser { onRead: loadMonitors._buf += data + "\n" }
        onRunningChanged: {
            if (running) return
            try {
                let data = JSON.parse(loadMonitors._buf)
                monitors.clear()
                for (let m of data) {
                    let current = m.width + "x" + m.height + "@" + parseFloat(m.refreshRate).toFixed(2)
                    let modes = []
                    if (m.availableModes && m.availableModes.length)
                        for (let am of m.availableModes) modes.push(am.replace("Hz", "").trim())
                    else modes.push(current)
                    monitors.append({
                        name: m.name || "Unknown",
                        description: m.description || m.model || "Display",
                        disabled: m.disabled === true,
                        modeStr: current,
                        mScale: m.scale || 1.0,
                        mTransform: m.transform || 0,
                        mX: m.x || 0,
                        mY: m.y || 0,
                        modesCsv: modes.join(",")
                    })
                }
            } catch (e) { console.log("DisplaysPage parse error: " + e) }
            loadMonitors._buf = ""
            page.loading = false
            page.dirty = false
        }
    }

    Process { id: applyProc }

    function applyAll() {
        let lua = "-- Generated by Quickshell Settings (Displays)\n\n"
        for (let i = 0; i < monitors.count; i++) {
            let m = monitors.get(i)
            if (m.disabled) {
                lua += "hl.monitor({\n    output = \"" + m.name + "\",\n    mode = \"disable\"\n})\n\n"
            } else {
                lua += "hl.monitor({\n"
                lua += "    output = \"" + m.name + "\",\n"
                lua += "    mode = \"" + m.modeStr + "\",\n"
                lua += "    position = \"" + m.mX + "x" + m.mY + "\",\n"
                lua += "    scale = " + parseFloat(m.mScale).toFixed(2) + ",\n"
                if (m.mTransform !== 0) lua += "    transform = " + m.mTransform + "\n"
                lua += "})\n\n"
            }
        }
        let b64 = Qt.btoa(unescape(encodeURIComponent(lua)))
        let path = "$HOME/.mydotfiles/com.ml4w.dotfiles/.config/hypr/monitors.lua"
        applyProc.command = ["bash", "-c",
            "mkdir -p $(dirname " + path + ") && echo '" + b64 + "' | base64 -d > " + path + " && hyprctl reload"]
        applyProc.running = true
        page.dirty = false
    }

    Text {
        visible: page.loading
        text: "Loading displays…"
        color: Theme.primary; opacity: 0.4; font.pixelSize: 13
    }

    Repeater {
        model: monitors
        delegate: StCard {
            id: card
            required property int index
            required property var model
            title: card.model.name + " · " + card.model.description

            readonly property var modeList: page.csvToList(card.model.modesCsv)
            readonly property var scaleList: page.scaleOptions(card.model.mScale)

            // Header: enable toggle
            StRow {
                icon: "󰍹"
                title: card.model.name
                subtitle: card.model.disabled ? "Disabled" : card.model.modeStr + "  ·  x" + parseFloat(card.model.mScale).toFixed(2)
                StToggle {
                    checked: !card.model.disabled
                    onToggled: (v) => { monitors.setProperty(card.index, "disabled", !v); page.dirty = true }
                }
            }

            StRow {
                visible: !card.model.disabled
                icon: "󰍹"
                title: "Resolution & refresh rate"
                StComboBox {
                    implicitWidth: 220
                    model: card.modeList
                    Component.onCompleted: currentIndex = Math.max(0, card.modeList.indexOf(card.model.modeStr))
                    onActivated: (i) => { monitors.setProperty(card.index, "modeStr", card.modeList[i]); page.dirty = true }
                }
            }

            StRow {
                visible: !card.model.disabled
                icon: "󰘎"
                title: "Scale"
                StComboBox {
                    implicitWidth: 140
                    model: card.scaleList
                    Component.onCompleted: currentIndex = Math.max(0, card.scaleList.indexOf(parseFloat(card.model.mScale).toFixed(2)))
                    onActivated: (i) => { monitors.setProperty(card.index, "mScale", parseFloat(card.scaleList[i])); page.dirty = true }
                }
            }

            StRow {
                visible: !card.model.disabled
                icon: "󰑵"
                title: "Orientation"
                StSegmented {
                    implicitWidth: 240
                    model: page.rotations
                    current: card.model.mTransform
                    onSelected: (v) => { monitors.setProperty(card.index, "mTransform", v); page.dirty = true }
                }
            }
        }
    }

    StCard {
        visible: !page.loading
        StRow {
            icon: "󰕲"
            title: "Visual arrangement"
            subtitle: "Drag monitors to reposition them"
            clickable: true
            onClicked: Quickshell.execDetached(["qs", "ipc", "call", "display", "open"])
            Text { text: "󰁔"; color: Theme.primary; opacity: 0.5; font.pixelSize: 16 }
        }
    }

    StButton {
        visible: !page.loading
        Layout.fillWidth: true
        implicitHeight: 46
        text: page.dirty ? "Apply changes" : "No changes"
        icon: "󰆓"
        accent: page.dirty
        enabled: page.dirty
        onClicked: page.applyAll()
    }

    // ── helpers ──
    function csvToList(csv) {
        let out = []
        for (let s of (csv || "").split(",")) if (s.trim() !== "") out.push(s.trim())
        return out
    }
    function scaleOptions(cur) {
        let base = ["1.00", "1.25", "1.50", "1.75", "2.00", "2.50", "3.00"]
        let c = parseFloat(cur).toFixed(2)
        if (base.indexOf(c) === -1) base.push(c)
        return base
    }
}
